### PR TITLE
Add hashtag feet ablity

### LINKED ISSUE #15: Embed hashtag
Could you extend this to make an embeddable feed for a hashtag?

Twitter recently took away this ability.  I had embedded the #KDE tag in Planet KDE from Twitter and I'm struggling to find a suitable replacement.

### PR DESCRIPTION
**Pull request by niccokunzmann**
You can choose between hashtags and users, fixes #15.

TODO still:
- [ ] header for hashtags
- [ ] check boost
- [ ] check reply
- [ ] add auto scroll

### CODE REVIEW

**Comment by niccokunzmann** [comment]
It is live now: https://mastodon-feed-iframe-embed.herokuapp.com/

**Comment by maphouse** [comment]
Is this live on https://www.mastofeed.com/ ? The hashtags I am trying aren't working.

**Comment by niccokunzmann** [comment]
[x] Added docker build.
[x] Added Heroku button.
[x] Added broken hashtag

At the moment, the API seems to have changed. I deployed
https://github.com/foss-wales/mastofeed/
here: https://mastofeed.hosted.quelltext.eu/

The feed is empty:
```
feed {
  '@context': 'https://www.w3.org/ns/activitystreams',
  id: 'https://toot.wales/tags/Wales',
  type: 'OrderedCollection'
}
```

```
wget -O a --header="accept: application/activity+json" https://toot.wales/tags/Wales
```


At the moment, this is not functional.
Feel free to ask about the other changes, too.

**Comment by maphouse** [comment]
Thanks for the update @niccokunzmann . yea the hashtags don't seem to work on your deployment. Is this something that you think can be solved in the future?

**Comment by niccokunzmann** [comment]
Yes, it can be solved and it might be that we are back at where we were before the PR.

**Pull request closed without merging**
